global:
  scrape_interval: 1m
  scrape_timeout: 60s # The application we monitor isn't very fast
# Testing Prometheus configuration
scrape_configs:
  - job_name: "vsphere_ci_sessions"
    static_configs:
      - targets:
        - localhost:8090
